# Generated by Django 5.2 on 2025-05-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_catagoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
